#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

TEST = devid_from_iscsi_name
TPS = tp_devid_from_in_001 \
	tp_devid_from_in_002 \
	tp_devid_from_in_003 \
	tp_devid_from_in_004

include ../Makefile.subdirs
