/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../include/ndmp.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */


bool_t
xdr_ndmp_header_message_type(xdrs, objp)
	XDR *xdrs;
	ndmp_header_message_type *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_pval(xdrs, objp)
	XDR *xdrs;
	ndmp_pval *objp;
{


	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->value, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_u_quad(xdrs, objp)
	XDR *xdrs;
	ndmp_u_quad *objp;
{


	if (!xdr_u_long(xdrs, &objp->high))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->low))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_error(xdrs, objp)
	XDR *xdrs;
	ndmp_error *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_message(xdrs, objp)
	XDR *xdrs;
	ndmp_message *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_header(xdrs, objp)
	XDR *xdrs;
	ndmp_header *objp;
{


	if (!xdr_u_long(xdrs, &objp->sequence))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->time_stamp))
		return (FALSE);
	if (!xdr_ndmp_header_message_type(xdrs, &objp->message_type))
		return (FALSE);
	if (!xdr_ndmp_message(xdrs, &objp->message_code))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->reply_sequence))
		return (FALSE);
	if (!xdr_ndmp_error(xdrs, &objp->error_code))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connect_open_request(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_open_request *objp;
{


	if (!xdr_u_short(xdrs, &objp->protocol_version))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connect_open_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_open_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_auth_type(xdrs, objp)
	XDR *xdrs;
	ndmp_auth_type *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_auth_text(xdrs, objp)
	XDR *xdrs;
	ndmp_auth_text *objp;
{


	if (!xdr_string(xdrs, &objp->auth_id, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->auth_password, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_auth_md5(xdrs, objp)
	XDR *xdrs;
	ndmp_auth_md5 *objp;
{


	if (!xdr_string(xdrs, &objp->auth_id, ~0))
		return (FALSE);
	if (!xdr_opaque(xdrs, objp->auth_digest, 16))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_auth_data(xdrs, objp)
	XDR *xdrs;
	ndmp_auth_data *objp;
{


	if (!xdr_ndmp_auth_type(xdrs, &objp->auth_type))
		return (FALSE);
	switch (objp->auth_type) {
	case NDMP_AUTH_NONE:
		break;
	case NDMP_AUTH_TEXT:
		if (!xdr_ndmp_auth_text(xdrs,
			&objp->ndmp_auth_data_u.auth_text))
			return (FALSE);
		break;
	case NDMP_AUTH_MD5:
		if (!xdr_ndmp_auth_md5(xdrs,
			&objp->ndmp_auth_data_u.auth_md5))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ndmp_auth_attr(xdrs, objp)
	XDR *xdrs;
	ndmp_auth_attr *objp;
{


	if (!xdr_ndmp_auth_type(xdrs, &objp->auth_type))
		return (FALSE);
	switch (objp->auth_type) {
	case NDMP_AUTH_NONE:
		break;
	case NDMP_AUTH_TEXT:
		break;
	case NDMP_AUTH_MD5:
		if (!xdr_opaque(xdrs, objp->ndmp_auth_attr_u.challenge, 64))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ndmp_connect_client_auth_request(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_client_auth_request *objp;
{


	if (!xdr_ndmp_auth_data(xdrs, &objp->auth_data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connect_client_auth_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_client_auth_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connect_server_auth_request(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_server_auth_request *objp;
{


	if (!xdr_ndmp_auth_attr(xdrs, &objp->client_attr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connect_server_auth_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_connect_server_auth_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_auth_data(xdrs, &objp->server_result))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_host_info_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_host_info_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->hostname, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->os_type, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->os_vers, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->hostid, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_server_info_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_server_info_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->vendor_name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->product_name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->revision_number, ~0))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->auth_type
			.auth_type_val,
		(u_int *) &objp->auth_type.auth_type_len, ~0,
		sizeof (ndmp_auth_type),
			(xdrproc_t)xdr_ndmp_auth_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_addr_type(xdrs, objp)
	XDR *xdrs;
	ndmp_addr_type *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_connection_type_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_connection_type_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->addr_types
			.addr_types_val,
		(u_int *) &objp->addr_types.addr_types_len, ~0,
		sizeof (ndmp_addr_type),
		(xdrproc_t)xdr_ndmp_addr_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_auth_attr_request(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_auth_attr_request *objp;
{


	if (!xdr_ndmp_auth_type(xdrs, &objp->auth_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_auth_attr_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_auth_attr_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_auth_attr(xdrs, &objp->server_attr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_butype_info(xdrs, objp)
	XDR *xdrs;
	ndmp_butype_info *objp;
{


	if (!xdr_string(xdrs, &objp->butype_name, ~0))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->default_env
		.default_env_val,
		(u_int *) &objp->default_env.default_env_len, ~0,
		sizeof (ndmp_pval),
		(xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->attrs))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_butype_attr_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_butype_attr_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->butype_info
			.butype_info_val,
		(u_int *) &objp->butype_info.butype_info_len, ~0,
		sizeof (ndmp_butype_info),
			(xdrproc_t)xdr_ndmp_butype_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_fs_info(xdrs, objp)
	XDR *xdrs;
	ndmp_fs_info *objp;
{


	if (!xdr_u_long(xdrs, &objp->unsupported))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fs_type, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fs_logical_device, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fs_physical_device, ~0))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->total_size))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->used_size))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->avail_size))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->total_inodes))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->used_inodes))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->fs_env.fs_env_val,
		(u_int *) &objp->fs_env.fs_env_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->fs_status, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_fs_info_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_fs_info_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->fs_info.fs_info_val, (u_int *) &objp->fs_info.fs_info_len, ~0,
		sizeof (ndmp_fs_info), (xdrproc_t)xdr_ndmp_fs_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_device_capability(xdrs, objp)
	XDR *xdrs;
	ndmp_device_capability *objp;
{


	if (!xdr_string(xdrs, &objp->device, ~0))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->attr))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->capability.capability_val, (u_int *) &objp->capability.capability_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_device_info(xdrs, objp)
	XDR *xdrs;
	ndmp_device_info *objp;
{


	if (!xdr_string(xdrs, &objp->model, ~0))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->caplist.caplist_val, (u_int *) &objp->caplist.caplist_len, ~0,
		sizeof (ndmp_device_capability), (xdrproc_t)xdr_ndmp_device_capability))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_tape_info_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_tape_info_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->tape_info.tape_info_val, (u_int *) &objp->tape_info.tape_info_len, ~0,
		sizeof (ndmp_device_info), (xdrproc_t)xdr_ndmp_device_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_scsi_info_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_scsi_info_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->scsi_info.scsi_info_val, (u_int *) &objp->scsi_info.scsi_info_len, ~0,
		sizeof (ndmp_device_info), (xdrproc_t)xdr_ndmp_device_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_class_list(xdrs, objp)
	XDR *xdrs;
	ndmp_class_list *objp;
{


	if (!xdr_u_short(xdrs, &objp->ext_class_id))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->ext_version.ext_version_val, (u_int *) &objp->ext_version.ext_version_len, ~0,
		sizeof (u_short), (xdrproc_t)xdr_u_short))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_class_version(xdrs, objp)
	XDR *xdrs;
	ndmp_class_version *objp;
{


	if (!xdr_u_short(xdrs, &objp->ext_class_id))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->ext_version))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_get_ext_list_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_get_ext_list_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->class_list.class_list_val, (u_int *) &objp->class_list.class_list_len, ~0,
		sizeof (ndmp_class_list), (xdrproc_t)xdr_ndmp_class_list))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_set_ext_list_request(xdrs, objp)
	XDR *xdrs;
	ndmp_config_set_ext_list_request *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->ndmp_selected_ext.ndmp_selected_ext_val, (u_int *) &objp->ndmp_selected_ext.ndmp_selected_ext_len, ~0,
		sizeof (ndmp_class_version), (xdrproc_t)xdr_ndmp_class_version))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_config_set_ext_list_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_config_set_ext_list_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_open_request(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_open_request *objp;
{


	if (!xdr_string(xdrs, &objp->device, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_open_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_open_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_close_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_close_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_get_state_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_get_state_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->target_controller))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->target_id))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->target_lun))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_reset_device_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_reset_device_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_execute_cdb_request(xdrs, objp)
	XDR *xdrs;
	ndmp_execute_cdb_request *objp;
{


	if (!xdr_u_long(xdrs, &objp->flags))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->timeout))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->datain_len))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->cdb.cdb_val, (u_int *) &objp->cdb.cdb_len, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->dataout.dataout_val, (u_int *) &objp->dataout.dataout_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_execute_cdb_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_execute_cdb_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_u_char(xdrs, &objp->status))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->dataout_len))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->datain.datain_val, (u_int *) &objp->datain.datain_len, ~0))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->ext_sense.ext_sense_val, (u_int *) &objp->ext_sense.ext_sense_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_open_mode(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_open_mode *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_open_request(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_open_request *objp;
{


	if (!xdr_string(xdrs, &objp->device, ~0))
		return (FALSE);
	if (!xdr_ndmp_tape_open_mode(xdrs, &objp->mode))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_open_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_open_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_close_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_close_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_get_state_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_get_state_reply *objp;
{

	rpc_inline_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_u_long(xdrs, &objp->unsupported))
			return (FALSE);
		if (!xdr_ndmp_error(xdrs, &objp->error))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->flags))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->file_num))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->soft_errors))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->block_size))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->blockno))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_INT32(buf, objp->flags);
			IXDR_PUT_U_INT32(buf, objp->file_num);
			IXDR_PUT_U_INT32(buf, objp->soft_errors);
			IXDR_PUT_U_INT32(buf, objp->block_size);
			IXDR_PUT_U_INT32(buf, objp->blockno);
#else
			IXDR_PUT_U_LONG(buf, objp->flags);
			IXDR_PUT_U_LONG(buf, objp->file_num);
			IXDR_PUT_U_LONG(buf, objp->soft_errors);
			IXDR_PUT_U_LONG(buf, objp->block_size);
			IXDR_PUT_U_LONG(buf, objp->blockno);
#endif
		}
		if (!xdr_ndmp_u_quad(xdrs, &objp->total_space))
			return (FALSE);
		if (!xdr_ndmp_u_quad(xdrs, &objp->space_remain))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_u_long(xdrs, &objp->unsupported))
			return (FALSE);
		if (!xdr_ndmp_error(xdrs, &objp->error))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->flags))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->file_num))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->soft_errors))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->block_size))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->blockno))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->flags = IXDR_GET_U_INT32(buf);
			objp->file_num = IXDR_GET_U_INT32(buf);
			objp->soft_errors = IXDR_GET_U_INT32(buf);
			objp->block_size = IXDR_GET_U_INT32(buf);
			objp->blockno = IXDR_GET_U_INT32(buf);
#else
			objp->flags = IXDR_GET_U_LONG(buf);
			objp->file_num = IXDR_GET_U_LONG(buf);
			objp->soft_errors = IXDR_GET_U_LONG(buf);
			objp->block_size = IXDR_GET_U_LONG(buf);
			objp->blockno = IXDR_GET_U_LONG(buf);
#endif
		}
		if (!xdr_ndmp_u_quad(xdrs, &objp->total_space))
			return (FALSE);
		if (!xdr_ndmp_u_quad(xdrs, &objp->space_remain))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_u_long(xdrs, &objp->unsupported))
		return (FALSE);
	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->flags))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->file_num))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->soft_errors))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->block_size))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->blockno))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->total_space))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->space_remain))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_mtio_op(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_mtio_op *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_mtio_request(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_mtio_request *objp;
{


	if (!xdr_ndmp_tape_mtio_op(xdrs, &objp->tape_op))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_mtio_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_mtio_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->resid_count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_write_request(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_write_request *objp;
{


	if (!xdr_bytes(xdrs, (char **)&objp->data_out.data_out_val, (u_int *) &objp->data_out.data_out_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_write_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_write_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_read_request(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_read_request *objp;
{


	if (!xdr_u_long(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_read_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_read_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->data_in.data_in_val, (u_int *) &objp->data_in.data_in_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_execute_cdb_request(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_execute_cdb_request *objp;
{


	if (!xdr_ndmp_execute_cdb_request(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_execute_cdb_request(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_execute_cdb_request *objp;
{


	if (!xdr_ndmp_execute_cdb_request(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tape_execute_cdb_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_tape_execute_cdb_reply *objp;
{


	if (!xdr_ndmp_execute_cdb_reply(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_scsi_execute_cdb_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_scsi_execute_cdb_reply *objp;
{


	if (!xdr_ndmp_execute_cdb_reply(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_operation(xdrs, objp)
	XDR *xdrs;
	ndmp_data_operation *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_state(xdrs, objp)
	XDR *xdrs;
	ndmp_data_state *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_halt_reason(xdrs, objp)
	XDR *xdrs;
	ndmp_data_halt_reason *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_tcp_addr(xdrs, objp)
	XDR *xdrs;
	ndmp_tcp_addr *objp;
{


	if (!xdr_u_long(xdrs, &objp->ip_addr))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->port))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->addr_env.addr_env_val, (u_int *) &objp->addr_env.addr_env_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_ipc_addr(xdrs, objp)
	XDR *xdrs;
	ndmp_ipc_addr *objp;
{


	if (!xdr_bytes(xdrs, (char **)&objp->comm_data.comm_data_val, (u_int *) &objp->comm_data.comm_data_len, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_addr(xdrs, objp)
	XDR *xdrs;
	ndmp_addr *objp;
{


	if (!xdr_ndmp_addr_type(xdrs, &objp->addr_type))
		return (FALSE);
	switch (objp->addr_type) {
	case NDMP_ADDR_LOCAL:
		break;
	case NDMP_ADDR_TCP:
		if (!xdr_array(xdrs, (char **)&objp->ndmp_addr_u.tcp_addr.tcp_addr_val, (u_int *) &objp->ndmp_addr_u.tcp_addr.tcp_addr_len, ~0,
			sizeof (ndmp_tcp_addr), (xdrproc_t)xdr_ndmp_tcp_addr))
			return (FALSE);
		break;
	case NDMP_ADDR_IPC:
		if (!xdr_ndmp_ipc_addr(xdrs, &objp->ndmp_addr_u.ipc_addr))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_ndmp_data_get_state_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_get_state_reply *objp;
{


	if (!xdr_u_long(xdrs, &objp->unsupported))
		return (FALSE);
	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_data_operation(xdrs, &objp->operation))
		return (FALSE);
	if (!xdr_ndmp_data_state(xdrs, &objp->state))
		return (FALSE);
	if (!xdr_ndmp_data_halt_reason(xdrs, &objp->halt_reason))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->bytes_processed))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->est_bytes_remain))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->est_time_remain))
		return (FALSE);
	if (!xdr_ndmp_addr(xdrs, &objp->data_connection_addr))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->read_offset))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->read_length))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_listen_request(xdrs, objp)
	XDR *xdrs;
	ndmp_data_listen_request *objp;
{


	if (!xdr_ndmp_addr_type(xdrs, &objp->addr_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_listen_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_listen_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_addr(xdrs, &objp->connect_addr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_connect_request(xdrs, objp)
	XDR *xdrs;
	ndmp_data_connect_request *objp;
{


	if (!xdr_ndmp_addr(xdrs, &objp->addr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_connect_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_connect_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_start_backup_request(xdrs, objp)
	XDR *xdrs;
	ndmp_data_start_backup_request *objp;
{


	if (!xdr_string(xdrs, &objp->butype_name, ~0))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->env.env_val, (u_int *) &objp->env.env_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_start_backup_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_start_backup_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_name(xdrs, objp)
	XDR *xdrs;
	ndmp_name *objp;
{


	if (!xdr_string(xdrs, &objp->original_path, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->destination_dir, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->other_name, ~0))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->node))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->fh_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_start_recover_request(xdrs, objp)
	XDR *xdrs;
	ndmp_data_start_recover_request *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->env.env_val, (u_int *) &objp->env.env_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->nlist.nlist_val, (u_int *) &objp->nlist.nlist_len, ~0,
		sizeof (ndmp_name), (xdrproc_t)xdr_ndmp_name))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->butype_name, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_start_recover_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_start_recover_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_abort_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_abort_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_stop_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_stop_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_data_get_env_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_data_get_env_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->env.env_val, (u_int *) &objp->env.env_len, ~0,
		sizeof (ndmp_pval), (xdrproc_t)xdr_ndmp_pval))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_mode(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_mode *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_state(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_state *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_pause_reason(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_pause_reason *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_halt_reason(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_halt_reason *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_set_record_size_request(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_set_record_size_request *objp;
{


	if (!xdr_u_long(xdrs, &objp->len))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_set_record_size_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_set_record_size_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_set_window_request(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_set_window_request *objp;
{


	if (!xdr_ndmp_u_quad(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->length))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_set_window_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_set_window_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_connect_request(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_connect_request *objp;
{


	if (!xdr_ndmp_mover_mode(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_ndmp_addr(xdrs, &objp->addr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_connect_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_connect_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_listen_request(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_listen_request *objp;
{


	if (!xdr_ndmp_mover_mode(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_ndmp_addr_type(xdrs, &objp->addr_type))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_listen_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_listen_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_addr(xdrs, &objp->connect_addr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_read_request(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_read_request *objp;
{


	if (!xdr_ndmp_u_quad(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->length))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_read_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_read_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_get_state_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_get_state_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	if (!xdr_ndmp_mover_mode(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_ndmp_mover_state(xdrs, &objp->state))
		return (FALSE);
	if (!xdr_ndmp_mover_pause_reason(xdrs, &objp->pause_reason))
		return (FALSE);
	if (!xdr_ndmp_mover_halt_reason(xdrs, &objp->halt_reason))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->record_size))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->record_num))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->bytes_moved))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->seek_position))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->bytes_left_to_read))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->window_offset))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->window_length))
		return (FALSE);
	if (!xdr_ndmp_addr(xdrs, &objp->data_connection_addr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_continue_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_continue_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_close_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_close_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_abort_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_abort_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_mover_stop_reply(xdrs, objp)
	XDR *xdrs;
	ndmp_mover_stop_reply *objp;
{


	if (!xdr_ndmp_error(xdrs, &objp->error))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_notify_data_halted_post(xdrs, objp)
	XDR *xdrs;
	ndmp_notify_data_halted_post *objp;
{


	if (!xdr_ndmp_data_halt_reason(xdrs, &objp->reason))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_connection_status_reason(xdrs, objp)
	XDR *xdrs;
	ndmp_connection_status_reason *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_notify_connection_status_post(xdrs, objp)
	XDR *xdrs;
	ndmp_notify_connection_status_post *objp;
{


	if (!xdr_ndmp_connection_status_reason(xdrs, &objp->reason))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->protocol_version))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->text_reason, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_notify_mover_halted_post(xdrs, objp)
	XDR *xdrs;
	ndmp_notify_mover_halted_post *objp;
{


	if (!xdr_ndmp_mover_halt_reason(xdrs, &objp->reason))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_notify_mover_paused_post(xdrs, objp)
	XDR *xdrs;
	ndmp_notify_mover_paused_post *objp;
{


	if (!xdr_ndmp_mover_pause_reason(xdrs, &objp->reason))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->seek_position))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_notify_data_read_post(xdrs, objp)
	XDR *xdrs;
	ndmp_notify_data_read_post *objp;
{


	if (!xdr_ndmp_u_quad(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->length))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_has_associated_message(xdrs, objp)
	XDR *xdrs;
	ndmp_has_associated_message *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_log_type(xdrs, objp)
	XDR *xdrs;
	ndmp_log_type *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_log_message_post(xdrs, objp)
	XDR *xdrs;
	ndmp_log_message_post *objp;
{


	if (!xdr_ndmp_log_type(xdrs, &objp->log_type))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->message_id))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->entry, ~0))
		return (FALSE);
	if (!xdr_ndmp_has_associated_message(xdrs, &objp->associated_message_valid))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->associated_message_sequence))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_recovery_status(xdrs, objp)
	XDR *xdrs;
	ndmp_recovery_status *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_log_file_post(xdrs, objp)
	XDR *xdrs;
	ndmp_log_file_post *objp;
{


	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_ndmp_recovery_status(xdrs, &objp->recovery_status))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_fs_type(xdrs, objp)
	XDR *xdrs;
	ndmp_fs_type *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_path(xdrs, objp)
	XDR *xdrs;
	ndmp_path *objp;
{


	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_nt_path(xdrs, objp)
	XDR *xdrs;
	ndmp_nt_path *objp;
{


	if (!xdr_ndmp_path(xdrs, &objp->nt_path))
		return (FALSE);
	if (!xdr_ndmp_path(xdrs, &objp->dos_path))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_file_name(xdrs, objp)
	XDR *xdrs;
	ndmp_file_name *objp;
{


	if (!xdr_ndmp_fs_type(xdrs, &objp->fs_type))
		return (FALSE);
	switch (objp->fs_type) {
	case NDMP_FS_UNIX:
		if (!xdr_ndmp_path(xdrs, &objp->ndmp_file_name_u.unix_name))
			return (FALSE);
		break;
	case NDMP_FS_NT:
		if (!xdr_ndmp_nt_path(xdrs, &objp->ndmp_file_name_u.nt_name))
			return (FALSE);
		break;
	default:
		if (!xdr_ndmp_path(xdrs, &objp->ndmp_file_name_u.other_name))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_ndmp_file_type(xdrs, objp)
	XDR *xdrs;
	ndmp_file_type *objp;
{


	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_file_stat(xdrs, objp)
	XDR *xdrs;
	ndmp_file_stat *objp;
{

	rpc_inline_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_u_long(xdrs, &objp->unsupported))
			return (FALSE);
		if (!xdr_ndmp_fs_type(xdrs, &objp->fs_type))
			return (FALSE);
		if (!xdr_ndmp_file_type(xdrs, &objp->ftype))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->mtime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->atime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->ctime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->owner))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->group))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->fattr))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_INT32(buf, objp->mtime);
			IXDR_PUT_U_INT32(buf, objp->atime);
			IXDR_PUT_U_INT32(buf, objp->ctime);
			IXDR_PUT_U_INT32(buf, objp->owner);
			IXDR_PUT_U_INT32(buf, objp->group);
			IXDR_PUT_U_INT32(buf, objp->fattr);
#else
			IXDR_PUT_U_LONG(buf, objp->mtime);
			IXDR_PUT_U_LONG(buf, objp->atime);
			IXDR_PUT_U_LONG(buf, objp->ctime);
			IXDR_PUT_U_LONG(buf, objp->owner);
			IXDR_PUT_U_LONG(buf, objp->group);
			IXDR_PUT_U_LONG(buf, objp->fattr);
#endif
		}
		if (!xdr_ndmp_u_quad(xdrs, &objp->size))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->links))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_u_long(xdrs, &objp->unsupported))
			return (FALSE);
		if (!xdr_ndmp_fs_type(xdrs, &objp->fs_type))
			return (FALSE);
		if (!xdr_ndmp_file_type(xdrs, &objp->ftype))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->mtime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->atime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->ctime))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->owner))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->group))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->fattr))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->mtime = IXDR_GET_U_INT32(buf);
			objp->atime = IXDR_GET_U_INT32(buf);
			objp->ctime = IXDR_GET_U_INT32(buf);
			objp->owner = IXDR_GET_U_INT32(buf);
			objp->group = IXDR_GET_U_INT32(buf);
			objp->fattr = IXDR_GET_U_INT32(buf);
#else
			objp->mtime = IXDR_GET_U_LONG(buf);
			objp->atime = IXDR_GET_U_LONG(buf);
			objp->ctime = IXDR_GET_U_LONG(buf);
			objp->owner = IXDR_GET_U_LONG(buf);
			objp->group = IXDR_GET_U_LONG(buf);
			objp->fattr = IXDR_GET_U_LONG(buf);
#endif
		}
		if (!xdr_ndmp_u_quad(xdrs, &objp->size))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->links))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_u_long(xdrs, &objp->unsupported))
		return (FALSE);
	if (!xdr_ndmp_fs_type(xdrs, &objp->fs_type))
		return (FALSE);
	if (!xdr_ndmp_file_type(xdrs, &objp->ftype))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->mtime))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->atime))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->ctime))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->owner))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->group))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->fattr))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->links))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_file(xdrs, objp)
	XDR *xdrs;
	ndmp_file *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->name.name_val, (u_int *) &objp->name.name_len, ~0,
		sizeof (ndmp_file_name), (xdrproc_t)xdr_ndmp_file_name))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->stat.stat_val, (u_int *) &objp->stat.stat_len, ~0,
		sizeof (ndmp_file_stat), (xdrproc_t)xdr_ndmp_file_stat))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->node))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->fh_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_fh_add_file_post(xdrs, objp)
	XDR *xdrs;
	ndmp_fh_add_file_post *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->files.files_val, (u_int *) &objp->files.files_len, ~0,
		sizeof (ndmp_file), (xdrproc_t)xdr_ndmp_file))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_dir(xdrs, objp)
	XDR *xdrs;
	ndmp_dir *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->name.name_val, (u_int *) &objp->name.name_len, ~0,
		sizeof (ndmp_file_name), (xdrproc_t)xdr_ndmp_file_name))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->node))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->parent))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_fh_add_dir_post(xdrs, objp)
	XDR *xdrs;
	ndmp_fh_add_dir_post *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->dirs.dirs_val, (u_int *) &objp->dirs.dirs_len, ~0,
		sizeof (ndmp_dir), (xdrproc_t)xdr_ndmp_dir))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_node(xdrs, objp)
	XDR *xdrs;
	ndmp_node *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->stats.stats_val, (u_int *) &objp->stats.stats_len, ~0,
		sizeof (ndmp_file_stat), (xdrproc_t)xdr_ndmp_file_stat))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->node))
		return (FALSE);
	if (!xdr_ndmp_u_quad(xdrs, &objp->fh_info))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ndmp_fh_add_node_post(xdrs, objp)
	XDR *xdrs;
	ndmp_fh_add_node_post *objp;
{


	if (!xdr_array(xdrs, (char **)&objp->nodes.nodes_val, (u_int *) &objp->nodes.nodes_len, ~0,
		sizeof (ndmp_node), (xdrproc_t)xdr_ndmp_node))
		return (FALSE);
	return (TRUE);
}
