#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Garrett D'Amore <garrett@damore.org>
# Copyright 2019 Joyent, Inc.
# Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
# Copyright 2023 Bill Sommerfeld <sommerfeld@alum.mit.edu>
# Copyright 2025 Oxide Computer Company
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 120
post =
outputdir = /var/tmp/test_results

[/opt/libc-tests/tests/symbols]
pre = setup
tests = [
	'assert_h',
	'ctype_h',
	'dirent_h',
	'fcntl_h',
	'locale_h',
	'math_h',
	'netdb_h',
	'pthread_h',
	'signal_h',
	'stdalign_h',
	'stddef_h',
	'stdio_h',
	'stdlib_h',
	'stdnoreturn_h',
	'string_h',
	'strings_h',
	'sys_atomic_h',
	'sys_mman_h',
	'sys_stat_h',
	'sys_time_h',
	'sys_timeb_h',
	'time_h',
	'threads_h',
	'ucontext_h',
	'unistd_h',
	'wchar_h',
	'wctype_h'
	 ]
timeout = 180

[/opt/libc-tests/tests/sym-cxx]
pre = setup
tests = [
	'cmath_h',
	'math_c99_h',
	'math_h',
	'math_iso_h'
	 ]
timeout = 180
