#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

.PARALLEL: $(SUBDIRS)

SUBDIRS = add_to_host_group \
	add_to_target_group \
	add_view_entry \
	clear_provider_data \
	create_host_group \
	create_target_group \
	delete_host_group \
	delete_target_group \
	devid_from_iscsi_name \
	devid_from_wwn \
	get_host_group_list \
	get_host_group_members \
	get_logical_unit_list \
	get_logical_unit_properties \
	get_provider_data \
	get_view_entry_list \
	get_state \
	get_target_group_list \
	get_target_group_members \
	get_target_list \
	get_target_properties \
	offline_logical_unit \
	offline_target \
	online_target \
	online_logical_unit \
	remove_from_host_group \
	remove_from_target_group \
	remove_view_entry \
	set_provider_data

include $(SRC)/test/Makefile.com
