#!/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015 Nexenta Systems, Inc. All rights reserved.
#

#
# Run this like:
# sh library-security-openssl-man-gen.sh 1 |\
#   diff -u library-security-openssl-man1.inc -
# sh library-security-openssl-man-gen.sh 3 |\
#   diff -u library-security-openssl-man3.inc -
#

gen_man_inc() {
    sed -n '2,15p' < $0

    cd $ROOT

    echo ""
    echo "# generated by library-security-openssl-man-gen.sh"
    echo ""
    find usr/share/man/man${1}openssl -type f -print |
      sed -e 's:^usr:file path=usr:' | sort

    echo ""
    find usr/share/man/man${1}openssl -type l -ls |
      sed -e 's:^.* usr/share:usr/share:' | sort |
      while read p x t
      do
        echo "link path=$p \\"
	echo "    target=$t"
      done
}

case "$1" in
[13])
	gen_man_inc "$1"
	;;
*)
	echo "usage: $0 { 1 | 3 }"
	exit 1;
	;;
esac
