/*
 * Please do not edit this file.
 * It was generated using ndrgen.
 */

#include <strings.h>
#include <libmlrpc/ndr.h>
#include "srvsvc1.ndl"

extern struct ndr_typeinfo ndt__char;
extern struct ndr_typeinfo ndt_s_char;
extern struct ndr_typeinfo ndt__uchar;
extern struct ndr_typeinfo ndt_s_uchar;
extern struct ndr_typeinfo ndt__wchar;
extern struct ndr_typeinfo ndt_s_wchar;
extern struct ndr_typeinfo ndt__short;
extern struct ndr_typeinfo ndt_s_short;
extern struct ndr_typeinfo ndt__ushort;
extern struct ndr_typeinfo ndt_s_ushort;
extern struct ndr_typeinfo ndt__long;
extern struct ndr_typeinfo ndt_s_long;
extern struct ndr_typeinfo ndt__ulong;
extern struct ndr_typeinfo ndt_s_ulong;



int ndr__mslm_NetShareInfo_0 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_0 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_0,	/* ndr_func */
	4,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	4,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_0 (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_0 *val = (struct mslm_NetShareInfo_0 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, shi0_netname, 0UL);

	return 1;
}



int ndr__mslm_NetShareInfo_0_result (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_0_result = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_0_result,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_0_result (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_0_result *val = (struct mslm_NetShareInfo_0_result *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, entriesread, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR_WITH_SIZE_IS (_mslm_NetShareInfo_0, entries, 4UL,
		val->entriesread);

	return 1;
}



int ndr__mslm_NetShareInfo_1 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_1 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_1,	/* ndr_func */
	12,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	12,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_1 (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_1 *val = (struct mslm_NetShareInfo_1 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, shi1_type, 4UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, shi1_netname, 0UL);
	NDR_MEMBER_PTR (s_wchar, shi1_comment, 8UL);

	return 1;
}



int ndr__mslm_NetShareInfo_1_result (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_1_result = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_1_result,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_1_result (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_1_result *val = (struct mslm_NetShareInfo_1_result *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, entriesread, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR_WITH_SIZE_IS (_mslm_NetShareInfo_1, entries, 4UL,
		val->entriesread);

	return 1;
}



int ndr__mslm_NetShareInfo_2 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_2 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_2,	/* ndr_func */
	32,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	32,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_2 (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_2 *val = (struct mslm_NetShareInfo_2 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, shi2_type, 4UL);
	NDR_MEMBER (_ulong, shi2_permissions, 12UL);
	NDR_MEMBER (_ulong, shi2_max_uses, 16UL);
	NDR_MEMBER (_ulong, shi2_current_uses, 20UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, shi2_netname, 0UL);
	NDR_MEMBER_PTR (s_wchar, shi2_comment, 8UL);
	NDR_MEMBER_PTR (s_wchar, shi2_path, 24UL);
	NDR_MEMBER_PTR (s_wchar, shi2_passwd, 28UL);

	return 1;
}



int ndr__mslm_NetShareInfo_2_result (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareInfo_2_result = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareInfo_2_result,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareInfo_2_result (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareInfo_2_result *val = (struct mslm_NetShareInfo_2_result *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, entriesread, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR_WITH_SIZE_IS (_mslm_NetShareInfo_2, entries, 4UL,
		val->entriesread);

	return 1;
}



int ndr__mslm_NetShareEnum_ru (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareEnum_ru = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_UNION,	/* flags */
	ndr__mslm_NetShareEnum_ru,	/* ndr_func */
	4,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	4,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareEnum_ru (struct ndr_reference *encl_ref)
{
	union mslm_NetShareEnum_ru *val = (union mslm_NetShareEnum_ru *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

    switch (encl_ref->switch_is) {
    case 0:
	NDR_MEMBER_PTR (_mslm_NetShareInfo_0_result, bufptr0, 0UL);
	break;

    case 1:
	NDR_MEMBER_PTR (_mslm_NetShareInfo_1_result, bufptr1, 0UL);
	break;

    case 2:
	NDR_MEMBER_PTR (_mslm_NetShareInfo_2_result, bufptr2, 0UL);
	break;

    default:
	NDR_MEMBER_PTR (_char, nullptr, 0UL);
	break;

    }


	return 1;
}



int ndr__mslm_NetShareEnum_result (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareEnum_result = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetShareEnum_result,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetShareEnum_result (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareEnum_result *val = (struct mslm_NetShareEnum_result *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, level, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_WITH_SWITCH_IS (_mslm_NetShareEnum_ru, ru, 4UL,
		val->level);

	return 1;
}



int ndr__mslm_NetShareEnum (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetShareEnum = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_OPERATION,	/* flags */
	ndr__mslm_NetShareEnum,	/* ndr_func */
	32,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	32,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 * [operation(15)]
 */
int
ndr__mslm_NetShareEnum (struct ndr_reference *encl_ref)
{
	struct mslm_NetShareEnum *val = (struct mslm_NetShareEnum *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all members in order */
    if (NDR_DIR_IS_IN) {
	NDR_TOPMOST_MEMBER_PTR (s_wchar, servername);
    }
	NDR_TOPMOST_MEMBER (_ulong, level);
	NDR_TOPMOST_MEMBER (_mslm_NetShareEnum_result, result);
    if (NDR_DIR_IS_IN) {
	NDR_TOPMOST_MEMBER (_ulong, prefmaxlen);
    }
    if (NDR_DIR_IS_OUT) {
	NDR_TOPMOST_MEMBER (_ulong, totalentries);
    }
	NDR_TOPMOST_MEMBER_PTR (_ulong, resume_handle);
    if (NDR_DIR_IS_OUT) {
	NDR_TOPMOST_MEMBER (_ulong, status);
    }

	return 1;
}



int ndr__mslm_SERVER_INFO_100 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_SERVER_INFO_100 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_SERVER_INFO_100,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_SERVER_INFO_100 (struct ndr_reference *encl_ref)
{
	struct mslm_SERVER_INFO_100 *val = (struct mslm_SERVER_INFO_100 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, sv100_platform_id, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, sv100_name, 4UL);

	return 1;
}



int ndr__mslm_SERVER_INFO_101 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_SERVER_INFO_101 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_SERVER_INFO_101,	/* ndr_func */
	24,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	24,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_SERVER_INFO_101 (struct ndr_reference *encl_ref)
{
	struct mslm_SERVER_INFO_101 *val = (struct mslm_SERVER_INFO_101 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, sv101_platform_id, 0UL);
	NDR_MEMBER (_ulong, sv101_version_major, 8UL);
	NDR_MEMBER (_ulong, sv101_version_minor, 12UL);
	NDR_MEMBER (_ulong, sv101_type, 16UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, sv101_name, 4UL);
	NDR_MEMBER_PTR (s_wchar, sv101_comment, 20UL);

	return 1;
}



int ndr__mslm_SERVER_INFO_102 (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_SERVER_INFO_102 = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_SERVER_INFO_102,	/* ndr_func */
	52,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	52,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_SERVER_INFO_102 (struct ndr_reference *encl_ref)
{
	struct mslm_SERVER_INFO_102 *val = (struct mslm_SERVER_INFO_102 *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, sv102_platform_id, 0UL);
	NDR_MEMBER (_ulong, sv102_version_major, 8UL);
	NDR_MEMBER (_ulong, sv102_version_minor, 12UL);
	NDR_MEMBER (_ulong, sv102_type, 16UL);
	NDR_MEMBER (_ulong, sv102_users, 24UL);
	NDR_MEMBER (_ulong, sv102_disc, 28UL);
	NDR_MEMBER (_ulong, sv102_hidden, 32UL);
	NDR_MEMBER (_ulong, sv102_announce, 36UL);
	NDR_MEMBER (_ulong, sv102_anndelta, 40UL);
	NDR_MEMBER (_ulong, sv102_licenses, 44UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_PTR (s_wchar, sv102_name, 4UL);
	NDR_MEMBER_PTR (s_wchar, sv102_comment, 20UL);
	NDR_MEMBER_PTR (s_wchar, sv102_userpath, 48UL);

	return 1;
}



int ndr__mslm_NetServerGetInfo_ru (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetServerGetInfo_ru = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_UNION,	/* flags */
	ndr__mslm_NetServerGetInfo_ru,	/* ndr_func */
	4,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	4,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetServerGetInfo_ru (struct ndr_reference *encl_ref)
{
	union mslm_NetServerGetInfo_ru *val = (union mslm_NetServerGetInfo_ru *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

    switch (encl_ref->switch_is) {
    case 100:
	NDR_MEMBER_PTR (_mslm_SERVER_INFO_100, info100, 0UL);
	break;

    case 101:
	NDR_MEMBER_PTR (_mslm_SERVER_INFO_101, info101, 0UL);
	break;

    case 102:
	NDR_MEMBER_PTR (_mslm_SERVER_INFO_102, info102, 0UL);
	break;

    default:
	NDR_MEMBER_PTR (_char, nullptr, 0UL);
	break;

    }


	return 1;
}



int ndr__mslm_NetServerGetInfo_result (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetServerGetInfo_result = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_STRUCT,	/* flags */
	ndr__mslm_NetServerGetInfo_result,	/* ndr_func */
	8,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	8,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 *  */
int
ndr__mslm_NetServerGetInfo_result (struct ndr_reference *encl_ref)
{
	struct mslm_NetServerGetInfo_result *val = (struct mslm_NetServerGetInfo_result *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all basic elements first */
	NDR_MEMBER (_ulong, level, 0UL);

	/* do all constructed elements w/o pointers */

	/* do members with pointers in order */
	NDR_MEMBER_WITH_SWITCH_IS (_mslm_NetServerGetInfo_ru, ru, 4UL,
		val->level);

	return 1;
}



int ndr__mslm_NetServerGetInfo (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__mslm_NetServerGetInfo = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_OPERATION,	/* flags */
	ndr__mslm_NetServerGetInfo,	/* ndr_func */
	20,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	20,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 * [operation(21)]
 */
int
ndr__mslm_NetServerGetInfo (struct ndr_reference *encl_ref)
{
	struct mslm_NetServerGetInfo *val = (struct mslm_NetServerGetInfo *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

	/* do all members in order */
    if (NDR_DIR_IS_IN) {
	NDR_TOPMOST_MEMBER_PTR (s_wchar, servername);
    }
    if (NDR_DIR_IS_IN) {
	NDR_TOPMOST_MEMBER (_ulong, level);
    }
    if (NDR_DIR_IS_OUT) {
	NDR_TOPMOST_MEMBER (_mslm_NetServerGetInfo_result, result);
    }
    if (NDR_DIR_IS_OUT) {
	NDR_TOPMOST_MEMBER (_ulong, status);
    }

	return 1;
}



int ndr__srvsvc_interface (struct ndr_reference *encl_ref);
struct ndr_typeinfo ndt__srvsvc_interface = {
	1,		/* NDR version */
	3,		/* alignment */
	NDR_F_INTERFACE,	/* flags */
	ndr__srvsvc_interface,	/* ndr_func */
	32,		/* pdu_size_fixed_part */
	0,		/* pdu_size_variable_part */
	32,		/* c_size_fixed_part */
	0,		/* c_size_variable_part */
};


/*
 * [interface(0)]
 */
int
ndr__srvsvc_interface (struct ndr_reference *encl_ref)
{
	union srvsvc_interface *val = (union srvsvc_interface *) encl_ref->datum;
	struct ndr_reference myref;

	(void) bzero(&myref, sizeof (myref));
	myref.enclosing = encl_ref;
	myref.stream = encl_ref->stream;

    switch (encl_ref->switch_is) {
    case 15:
	NDR_PARAMS_MEMBER (_mslm_NetShareEnum, NetShareEnum);
	break;

    case 21:
	NDR_PARAMS_MEMBER (_mslm_NetServerGetInfo, NetServerGetInfo);
	break;

    default:
	NDR_SET_ERROR(encl_ref, NDR_ERR_SWITCH_VALUE_INVALID);
	return 0;
	break;
    }


	return 1;
}
